edition = "2021"
version = "Two"

unstable_features = true

condense_wildcard_suffixes = true

format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true

imports_granularity = "Module"

normalize_doc_attributes = true

reorder_impl_items = true
reorder_modules = false

group_imports = "StdExternalCrate"

trailing_semicolon = false

use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true

fn_call_width = 80
struct_lit_width = 80

overflow_delimited_expr = true
